# action.yaml
name: 'Keyword Emphasizer'

description: 'A GitHub Action that takes an input and returns the square of the number'

inputs:
  num:
    description: 'Enter a number'
    required: true
    default: "1"

outputs:
  num_squared:
    description: 'Square of the input'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-square.outputs.num_squared }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pipenv'
        cache-dependency-path: ./Pipfile.lock

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv
      shell: bash

    - id: cache-pipenv
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --dev
      shell: bash

    - name: Pass Inputs to Shell
      run: |
        echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    
    - name: Fetch the number's square
      id: get-square
      run: python src/get_num_square.py
      shell: bash
