FROM python:3.9

# Set the working directory
WORKDIR /app/src

COPY ["Pipfile", "Pipfile.lock", "./"]

RUN pip install --upgrade pip
RUN pip install pipenv && \
    pipenv install --deploy --system --ignore-pipfile

COPY hwr_analyzer ./hwr_analyzer

ENV APP_ENV build
